### ISSUE TITLE
Update pot image sizes

### ISSUE THREAD

**Issue by jamiehaywood** [rknightuk/monzo-pot-image-generator#17]
With the revamp of pots, the image sizes have shrunk. It would be good to add a feature to center align / shrink the text. Happy to raise a PR.
![IMG_4368](https://github.com/rknightuk/monzo-pot-image-generator/assets/26779712/22e7a9dc-51d0-43a0-aa1d-489985097554)

**Comment by Artemis-Hound** [comment]
No option to center the text as far as I can see but there is a "square" option on the site now which can be used to adjust your pot images appropriately

**Comment by jamiehaywood** [comment]
great thanks @Adam-Kay. Great repo.
